<template>
  <v-container>
    <v-row justify="center">
      <v-col cols="auto">
        <h1 class="page-title">Submit</h1>
      </v-col>
    </v-row>
    <v-row justify="center">
      <v-col cols="12">
        <v-alert
          class="text-center submission-link"
          variant="tonal"
          color="red"
        >
          <p class="text-center pl-4">Submissions are <em>CLOSED</em>.</p>
          <h2>
            <NuxtLink to="/call-for-papers" class="calendar-link">
              <v-icon icon="mdi-help-circle-outline" size="x-small" />
              <span class="pl-1 text-decoration-underline"
                >Topics of Interest
              </span>
            </NuxtLink>
          </h2>
          <h2>
            <NuxtLink to="/special-sessions" class="calendar-link">
              <v-icon icon="mdi-help-circle-outline" size="x-small" />
              <span class="pl-1 text-decoration-underline"
                >Special Sessions
              </span>
            </NuxtLink>
          </h2>
        </v-alert>
      </v-col>
      <v-col cols="12">
        <h2 class="page-title">Paper Submission Guidelines</h2>
      </v-col>
      <v-col cols="12">
        <p class="page-content">
          All papers must be original and not simultaneously submitted to
          another journal or conference. A submission implies willingness by the
          authors to register and present their work if the paper is accepted
          for presentation at the conference. Accepted papers will be submitted
          for inclusion into
          <NuxtLink
            to="https://ieeexplore.ieee.org/Xplore/home.jsp"
            target="_blank"
            >IEEE Xplore</NuxtLink
          >
          subject to meeting IEEE Xplore's scope and quality requirements.
        </p>
        <p class="page-content pt-4">
          Full Papers (between 5 and 8 pages) will be reviewed for acceptance in
          one or more of the following topics, typically involving some aspect
          of information, data or sensor fusion. Submitted papers must be
          formatted according to the IEEE Xplore template (A4 or Letter Size
          Paper), provided by IEEE
          <NuxtLink
            to="https://www.ieee.org/conferences/publishing/templates.html"
            target="_blank"
            >here</NuxtLink
          >, to be considered for acceptance and publication.
        </p>
      </v-col>
      <v-col cols="12">
        <p class="page-content">Author guidelines</p>
        <ul class="page-content no-list pl-md-6 pt-2">
          <li class="pt-2">
            A1 – Authors must submit their own original work only.
          </li>
          <li class="pt-2">
            A2 – Authors must not omit the main references done by others and
            related to their works.
          </li>
          <li class="pt-2">
            A3 – Authors must follow typesetting guidelines (templates) of the
            FUSION conference (<NuxtLink
              to="https://www.ieee.org/conferences/publishing/templates.html"
              target="_blank"
              >see here</NuxtLink
            >).
          </li>
          <li class="pt-2">
            A4 – Authors must agree with ISIF copyright agreement, once the
            paper is accepted for presentation.
          </li>
          <li class="pt-2">
            A5 – Authors must employ professional language and they must avoid
            excessive verbosity that would dilute the technical clarity.
          </li>
          <li class="pt-2">
            A6 – Authors must comply with the guidelines on the use and
            disclosure of content generated by artificial intelligence (AI)
            specified in the
            <NuxtLink
              to="https://pspb.ieee.org/images/files/PSPB/opsmanual.pdf"
              target="_blank"
              >IEEE Publication Services and Products Board Operations
              Manual</NuxtLink
            >:
            <br />
            <ul class="page-content no-list ml-md-4 pl-2 mt-4 border-s-xl">
              <li>
                <em
                  >8.2.1 Publication Principles | B. RESPONSIBILITIES OF AUTHORS
                  OF ARTICLES PUBLISHED BY IEEE</em
                >
              </li>
              <li class="pt-2">
                <em
                  >10. The use of content generated by artificial intelligence
                  (AI) in an article (including but not limited to text,
                  figures, images, and code) shall be disclosed in the
                  acknowledgments section of any article submitted to an IEEE
                  publication. The AI system used shall be identified, and
                  specific sections of the article that use AI-generated content
                  shall be identified and accompanied by a brief explanation
                  regarding the level at which the AI system was used to
                  generate the content.</em
                >
              </li>
              <li class="pt-2">
                <em
                  >The use of AI systems for editing and grammar enhancement is
                  common practice and, as such, is generally outside the intent
                  of the above policy. In this case, disclosure as noted above
                  is recommended.</em
                >
              </li>
              <li class="pt-2">
                [<NuxtLink
                  to="https://pspb.ieee.org/images/files/PSPB/opsmanual.pdf"
                  target="_blank"
                  >IEEE Publication Services and Products Board Operations
                  Manual</NuxtLink
                >, 2023, pp. 98–99, para. 10]
              </li>
            </ul>
          </li>
        </ul>
      </v-col>
      <v-col cols="12">
        <h2 class="page-title">Template</h2>
      </v-col>
      <v-col cols="12">
        <p class="page-content">
          The submission of the review manuscript consists of a unique file, in
          PDF format. Submitted papers MUST be formatted according to the IEEE
          Xplore template (A4 or Letter Size Paper). Templates and other
          supporting files for various types of operating systems can be
          downloaded using the following link:
          <NuxtLink
            to="https://www.ieee.org/conferences/publishing/templates.html"
            target="_blank"
            >IEEE Xplore template</NuxtLink
          >. Papers that are not correctly formatted will be desk-rejected.
        </p>
        <p class="page-content pt-4">
          IEEE conference templates contain guidance text for composing and
          formatting conference papers. Please ensure that all guidance text is
          removed from your conference paper before submission to the
          conference. Failure to remove template text from your paper may result
          in your paper not being published.
        </p>
      </v-col>
      <v-col cols="12">
        <h2 class="page-title">Submission of Final Manuscripts</h2>
      </v-col>
      <v-col cols="12">
        <p class="page-content">
          After receiving your paper acceptance notification, follow the steps below to ensure the proper final submission of your paper and inclusion in the conference proceedings. Detailed instructions can be found below the process steps.
        </p>
        <ul class="page-content no-list pt-2 pl-md-6">
          <li class="pt-2">
            – Review the paper (5-8 pages) to ensure it meets the correct IEEE template (see above).
          </li>
          <li class="pt-2">
            – Check your accepted final paper through IEEE PDF eXpress (FUSION 2025 conference ID: 65864X).
          </li>
          <li class="pt-2">
          – Register for the conference by the early-bird deadline of June 1, 2025 AND provide your CMT paper ID in the registration system.
          </li>
          <li class="pt-2">
           - Complete the ISIF Copyright Form and upload the signed form here by June 1, 2025.
          </li>
          <li class="pt-2">
           - Upload your Final Paper Manuscript by June 1, 2025 in CMT.
          </li>
        </ul>
</v-col>
      
      <v-col cols="12">
        <h2 class="page-title">Compatibility Test (IEEE PDF eXpress)</h2>
      </v-col>
     <v-col cols="12">
     <p class="page-content pt-4">
      Final versions of accepted papers are required to pass the compatibility test in IEEE PDF eXpress. It will allow you to convert your MS Word, LaTeX, or a range of other source files into IEEE Xplore-compatible files. You must use PDF eXpress to check your own PDF file. Please follow the steps below to make sure your file is compliant with IEEE Xplore®:
     </p>
    
      <ul class="page-content no-list pt-2 pl-md-6">
          <li class="pt-2">
            – Go to the IEEE PDF eXpress website at https://ieee-pdf-express.org
          </li>
          <li class="pt-2">
            – Click on ‘New User’ to create your own IEEE PDF eXpress account for Fusion 2025 using the Conference ID provided –65864X.
          </li>
          <li class="pt-2">
          – If you have used IEEE PDF eXpress before, the system will recognize you as an existing user, but you still need to set up your account for Fusion 2025.
          </li>
          <li class="pt-2">
           - Upload source file(s) for conversion and/or PDF(s) for checking. The site contains extensive instructions, resources, helpful hints, and access to technical support.     
          </li>
          <li class="pt-2">
           - Proofread the generated PDF file thoroughly. There could be missing symbols, equations, graphs, and also reported errors. If you have reported errors, please update the source file 
          </li>
        </ul>
        <p class="page-content pt-4">Upon using IEEE PDF eXpress and passing the compatibility test, you will receive an email from IEEE PDF eXpress Site Services (support@incontrolproductions.net) with your manuscript (PDF file) attached. Please download this PDF file of your manuscript and upload it to the CMT submission system.</p>

      </v-col>
      
      <v-col cols="12">
        <h2 class="page-title">Presentation Instructions</h2>
      </v-col>
      <v-col cols="12">
        <p class="page-content">
          One of the co-authors must register for the conference at the regular
          or student rate by June 1st and present the paper on-site at the
          conference in Rio de Janeiro for it to be included in both IEEE Xplore
          and the online ISIF FUSION 2025 proceedings:
        </p>
        <ul class="page-content no-list pt-2 pl-md-6">
          <li class="pt-2">
            – Each paper will be allocated 15 minutes for its presentation,
            which will be followed by 5 minutes for questions;
          </li>
          <li class="pt-2">
            – Each room has a computer with MS PowerPoint and Acrobat Reader;
          </li>
          <li class="pt-2">
            – The final conference programme and full room allocations and
            scheduling details will be available by mid-June. All rooms are on
            the ground floor and within 2 minutes walking distance.
          </li>
        </ul>
      </v-col>
    </v-row>
    <v-row>
      <v-col cols="12">
        <h2 class="page-title">Important Dates</h2>
        <ul class="page-content no-list pt-2 pl-md-6">
          <li class="pt-2">
            – Full paper submission:
            <span class="text-decoration-line-through">March 1st, 2025</span>
            March 16th, 2025, Anywhere on Earth (AoE)
          </li>
          <li class="pt-2">
            – Notification of paper acceptance: May 1st, 2025, Anywhere on Earth
            (AoE)
          </li>
          <li class="pt-2">
            – Final paper submission: June 1st, 2025, Anywhere on Earth (AoE)
          </li>
        </ul>
      </v-col>
      <v-col cols="12"
    /></v-row>
  </v-container>
</template>

<style scoped>
.submission-link p {
  font-size: xx-large;
  font-weight: bold;
}
.calendar-link {
  font-size: xx-large !important;
  color: #005047;
  text-decoration: none;
}
</style>
